general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(1e1e2e)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    outer_color = rgb(cdd6f4)
    inner_color = rgb(181825)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = <span foreground="##cdd6f4">Password</span>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(cdd6f4)
    font_size = 72
    font_family = PragmataProLiga
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A, %B %d')"
    color = rgb(cdd6f4)
    font_size = 20
    font_family = PragmataProLiga
    position = 0, 70
    halign = center
    valign = center
}
