foreground         #3c3c3c
background         #f3f2f3
background_opacity 1.0
cursor             #3c3c3c

active_tab_foreground     #f3f2f3
active_tab_background     #3c3c3c
inactive_tab_foreground   #3c3c3c
inactive_tab_background   #f3f2f3

active_border_color   #3c3c3c
inactive_border_color #f3f2f3
bell_border_color     #5D4A55

color0       #f3f2f3
color8       #b6b5b6
color1       #5D4A55
color9       #5D4A55
color2       #9F2905
color10      #9F2905
color3       #B25633
color11      #B25633
color4       #E06017
color12      #E06017
color5       #DE894C
color13      #DE894C
color6       #7F738E
color14      #7F738E
color7       #3c3c3c
color15      #3c3c3c
